version: "3.9"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
  web:
    build: .
    command: "python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    volumes:
      - ./src:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

