version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: todoapp
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: django
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:alpine
    restart: always
  web:
    build: .
    command: >
      /bin/sh -c "python3 manage.py migrate
                  && python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    volumes:
      - ./src:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db-data:
    driver: local